# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifion', '0003_auto_20170127_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
