# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifion', '0004_submission_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='lifion.Question'),
        ),
    ]
