# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifion', '0006_auto_20170127_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='submitters',
            field=models.ManyToManyField(related_name='requested_surveys', to=settings.AUTH_USER_MODEL),
        ),
    ]
