# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifion', '0007_survey_submitters'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
