# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifion', '0008_submission_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifion.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifion.Question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lifion.Submission')),
            ],
            options={
                'db_table': 'question_response',
            },
        ),
    ]
